version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Entering backend folder"
      - cd backend
      - echo "Installing dependencies into package directory"
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Build phase completed successfully"

artifacts:
  base-directory: backend
  files:
    - '**/*'
